apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: example
  region: us-east-1
  version: "1.32"
iam:
  withOIDC: true
vpc:
  nat:
    gateway: Disable
karpenter:
  version: "1.2.0"
  createServiceAccount: true
  withSpotInterruptionQueue: true
managedNodeGroups:
  - name: service
    desiredCapacity: 1
    maxSize: 2
    minSize: 1
    amiFamily: AmazonLinux2
    availabilityZones:
      - us-east-1a
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        externalDNS: true
    labels:
      juno-innovations.com/service: "true"
    instanceSelector:
      vCPUs: 4
      memory: "8"
      cpuArchitecture: x86_64
